config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
    resources :doses, only: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
   validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
      if @cocktail.save
        redirect_to cocktail_path(@cocktail)
      else
        render :new
      end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end


  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.delete
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
_form.html.erb

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<p id="notice"><%= notice %></p>

<h1>Cocktails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktail.each do |restaurant| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
        <td><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cocktails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td class=""><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
        <td><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>

<h3>Preparation</h3>
<ul>
  <% @cocktail.doses.each do |dose| %>
    <li>
      <%= dose.description %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail), class: 'btn btn-primary' %>
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>